[build]
builder = "nixpacks"

[variables]
PHP_INI_SCAN_DIR = "/app/apps/api"

[phases.setup]
nixPkgs = [
  "php84",
  "php84Packages.composer",
  "php84Extensions.pdo",
  "php84Extensions.pdo_pgsql",
  "php84Extensions.mbstring",
  "php84Extensions.bcmath",
  "php84Extensions.gd",
  "php84Extensions.redis",
]

[phases.install]
cmds = ["cd apps/api && composer install --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = [
  "cd apps/api && php artisan storage:link",
  "cd apps/api && php artisan octane:install --server=frankenphp",
  "cd apps/api && php artisan config:cache",
  "cd apps/api && php artisan route:cache",
  "cd apps/api && php artisan view:cache"
]

[start]
cmd = "bash apps/api/start.sh"