// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAuthSessionsByIdData, DeleteAuthSessionsByIdResponses, DeleteOrgDepartmentsByDepartmentIdTeamsByTeamIdData, DeleteOrgDepartmentsByDepartmentIdTeamsByTeamIdResponses, DeleteOrgDepartmentsByIdData, DeleteOrgDepartmentsByIdResponses, DeleteOrgDesignationsByIdData, DeleteOrgDesignationsByIdResponses, DeleteOrgUsersByIdData, DeleteOrgUsersByIdResponses, GetAuthProfileData, GetAuthProfileResponses, GetAuthSessionsData, GetAuthSessionsResponses, GetDirectoryData, GetDirectoryResponses, GetHealthData, GetHealthResponses, GetOrgDepartmentsByIdData, GetOrgDepartmentsByIdResponses, GetOrgDepartmentsData, GetOrgDepartmentsResponses, GetOrgDesignationsData, GetOrgDesignationsResponses, GetOrgUsersByIdData, GetOrgUsersByIdResponses, GetOrgUsersData, GetOrgUsersResponses, PostAuthChangePasswordData, PostAuthChangePasswordResponses, PostAuthForgotPasswordData, PostAuthForgotPasswordResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutResponses, PostAuthResetPasswordData, PostAuthResetPasswordResponses, PostAuthRoleSelectData, PostAuthRoleSelectErrors, PostAuthRoleSelectResponses, PostOrgDepartmentsByDepartmentIdTeamsData, PostOrgDepartmentsByDepartmentIdTeamsResponses, PostOrgDepartmentsData, PostOrgDepartmentsResponses, PostOrgDesignationsData, PostOrgDesignationsResponses, PostOrgUsersData, PostOrgUsersResponses, PutAuthProfileData, PutAuthProfileResponses, PutOrgDepartmentsByIdData, PutOrgDepartmentsByIdResponses, PutOrgDesignationsByIdData, PutOrgDesignationsByIdResponses, PutOrgUsersByIdData, PutOrgUsersByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health check endpoint
 *
 * Returns the health status of the API server.
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Authenticate a user
 *
 * Login using email or employee ID and password.
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostAuthLoginData, ThrowOnError>): RequestResult<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError> => (options.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Select active role
 *
 * Sets the active role for the current session.
 */
export const postAuthRoleSelect = <ThrowOnError extends boolean = false>(options: Options<PostAuthRoleSelectData, ThrowOnError>): RequestResult<PostAuthRoleSelectResponses, PostAuthRoleSelectErrors, ThrowOnError> => (options.client ?? client).post<PostAuthRoleSelectResponses, PostAuthRoleSelectErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/role/select',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Request password reset
 */
export const postAuthForgotPassword = <ThrowOnError extends boolean = false>(options: Options<PostAuthForgotPasswordData, ThrowOnError>): RequestResult<PostAuthForgotPasswordResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostAuthForgotPasswordResponses, unknown, ThrowOnError>({
    url: '/auth/forgot-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset password using token
 */
export const postAuthResetPassword = <ThrowOnError extends boolean = false>(options: Options<PostAuthResetPasswordData, ThrowOnError>): RequestResult<PostAuthResetPasswordResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostAuthResetPasswordResponses, unknown, ThrowOnError>({
    url: '/auth/reset-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change password (first login or profile)
 */
export const postAuthChangePassword = <ThrowOnError extends boolean = false>(options: Options<PostAuthChangePasswordData, ThrowOnError>): RequestResult<PostAuthChangePasswordResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostAuthChangePasswordResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List active sessions
 */
export const getAuthSessions = <ThrowOnError extends boolean = false>(options?: Options<GetAuthSessionsData, ThrowOnError>): RequestResult<GetAuthSessionsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAuthSessionsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/sessions',
    ...options
});

/**
 * Revoke a specific session
 */
export const deleteAuthSessionsById = <ThrowOnError extends boolean = false>(options: Options<DeleteAuthSessionsByIdData, ThrowOnError>): RequestResult<DeleteAuthSessionsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteAuthSessionsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/sessions/{id}',
    ...options
});

/**
 * Logout current session
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>): RequestResult<PostAuthLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<PostAuthLogoutResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

/**
 * Get current user profile
 */
export const getAuthProfile = <ThrowOnError extends boolean = false>(options?: Options<GetAuthProfileData, ThrowOnError>): RequestResult<GetAuthProfileResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetAuthProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/profile',
    ...options
});

/**
 * Update current user profile
 */
export const putAuthProfile = <ThrowOnError extends boolean = false>(options: Options<PutAuthProfileData, ThrowOnError>): RequestResult<PutAuthProfileResponses, unknown, ThrowOnError> => (options.client ?? client).put<PutAuthProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get employee directory
 */
export const getDirectory = <ThrowOnError extends boolean = false>(options?: Options<GetDirectoryData, ThrowOnError>): RequestResult<GetDirectoryResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetDirectoryResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/directory',
    ...options
});

/**
 * List departments
 */
export const getOrgDepartments = <ThrowOnError extends boolean = false>(options?: Options<GetOrgDepartmentsData, ThrowOnError>): RequestResult<GetOrgDepartmentsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetOrgDepartmentsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/departments',
    ...options
});

/**
 * Create department
 */
export const postOrgDepartments = <ThrowOnError extends boolean = false>(options: Options<PostOrgDepartmentsData, ThrowOnError>): RequestResult<PostOrgDepartmentsResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostOrgDepartmentsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/departments',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete department
 */
export const deleteOrgDepartmentsById = <ThrowOnError extends boolean = false>(options: Options<DeleteOrgDepartmentsByIdData, ThrowOnError>): RequestResult<DeleteOrgDepartmentsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteOrgDepartmentsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/departments/{id}',
    ...options
});

/**
 * Get department
 */
export const getOrgDepartmentsById = <ThrowOnError extends boolean = false>(options: Options<GetOrgDepartmentsByIdData, ThrowOnError>): RequestResult<GetOrgDepartmentsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetOrgDepartmentsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/departments/{id}',
    ...options
});

/**
 * Update department
 */
export const putOrgDepartmentsById = <ThrowOnError extends boolean = false>(options: Options<PutOrgDepartmentsByIdData, ThrowOnError>): RequestResult<PutOrgDepartmentsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).put<PutOrgDepartmentsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/departments/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create team
 */
export const postOrgDepartmentsByDepartmentIdTeams = <ThrowOnError extends boolean = false>(options: Options<PostOrgDepartmentsByDepartmentIdTeamsData, ThrowOnError>): RequestResult<PostOrgDepartmentsByDepartmentIdTeamsResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostOrgDepartmentsByDepartmentIdTeamsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/departments/{departmentId}/teams',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete team
 */
export const deleteOrgDepartmentsByDepartmentIdTeamsByTeamId = <ThrowOnError extends boolean = false>(options: Options<DeleteOrgDepartmentsByDepartmentIdTeamsByTeamIdData, ThrowOnError>): RequestResult<DeleteOrgDepartmentsByDepartmentIdTeamsByTeamIdResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteOrgDepartmentsByDepartmentIdTeamsByTeamIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/departments/{departmentId}/teams/{teamId}',
    ...options
});

/**
 * List designations
 */
export const getOrgDesignations = <ThrowOnError extends boolean = false>(options?: Options<GetOrgDesignationsData, ThrowOnError>): RequestResult<GetOrgDesignationsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetOrgDesignationsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/designations',
    ...options
});

/**
 * Create designation
 */
export const postOrgDesignations = <ThrowOnError extends boolean = false>(options: Options<PostOrgDesignationsData, ThrowOnError>): RequestResult<PostOrgDesignationsResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostOrgDesignationsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/designations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete designation
 */
export const deleteOrgDesignationsById = <ThrowOnError extends boolean = false>(options: Options<DeleteOrgDesignationsByIdData, ThrowOnError>): RequestResult<DeleteOrgDesignationsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteOrgDesignationsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/designations/{id}',
    ...options
});

/**
 * Update designation
 */
export const putOrgDesignationsById = <ThrowOnError extends boolean = false>(options: Options<PutOrgDesignationsByIdData, ThrowOnError>): RequestResult<PutOrgDesignationsByIdResponses, unknown, ThrowOnError> => (options.client ?? client).put<PutOrgDesignationsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/designations/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List users
 */
export const getOrgUsers = <ThrowOnError extends boolean = false>(options?: Options<GetOrgUsersData, ThrowOnError>): RequestResult<GetOrgUsersResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetOrgUsersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/users',
    ...options
});

/**
 * Create user
 */
export const postOrgUsers = <ThrowOnError extends boolean = false>(options: Options<PostOrgUsersData, ThrowOnError>): RequestResult<PostOrgUsersResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostOrgUsersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete user
 */
export const deleteOrgUsersById = <ThrowOnError extends boolean = false>(options: Options<DeleteOrgUsersByIdData, ThrowOnError>): RequestResult<DeleteOrgUsersByIdResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteOrgUsersByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/users/{id}',
    ...options
});

/**
 * Get user
 */
export const getOrgUsersById = <ThrowOnError extends boolean = false>(options: Options<GetOrgUsersByIdData, ThrowOnError>): RequestResult<GetOrgUsersByIdResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetOrgUsersByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/users/{id}',
    ...options
});

/**
 * Update user
 */
export const putOrgUsersById = <ThrowOnError extends boolean = false>(options: Options<PutOrgUsersByIdData, ThrowOnError>): RequestResult<PutOrgUsersByIdResponses, unknown, ThrowOnError> => (options.client ?? client).put<PutOrgUsersByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/org/users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
