// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000/api' | 'https://api.games4kings.com/api' | (string & {});
};

export type User = {
    id?: number;
    name?: string;
    email?: string;
    employee_id?: string;
    avatar_url?: string;
    must_change_password?: boolean;
    status?: string;
    roles?: Array<string>;
};

export type AuthResponse = {
    token?: string;
    user?: User;
    active_role?: string | null;
};

export type Session = {
    id?: number;
    device_name?: string;
    ip_address?: string;
    last_used_at?: string;
    is_current?: boolean;
};

export type Department = {
    id?: number;
    name?: string;
    description?: string | null;
    teams?: Array<Team>;
};

export type Team = {
    id?: number;
    department_id?: number;
    name?: string;
    description?: string | null;
};

export type Designation = {
    id?: number;
    name?: string;
    description?: string | null;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * OK
     */
    200: {
        status?: string;
    };
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type PostAuthLoginData = {
    body: {
        /**
         * Email or Employee ID
         */
        identifier: string;
        password: string;
        /**
         * Identifier for the device
         */
        device_name?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Account locked
     */
    423: unknown;
};

export type PostAuthLoginResponses = {
    /**
     * Successful authentication
     */
    200: AuthResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRoleSelectData = {
    body: {
        role: string;
    };
    path?: never;
    query?: never;
    url: '/auth/role/select';
};

export type PostAuthRoleSelectErrors = {
    /**
     * Role not assigned to user
     */
    403: unknown;
};

export type PostAuthRoleSelectResponses = {
    /**
     * Role selected successfully
     */
    200: AuthResponse;
};

export type PostAuthRoleSelectResponse = PostAuthRoleSelectResponses[keyof PostAuthRoleSelectResponses];

export type PostAuthForgotPasswordData = {
    body: {
        identifier: string;
        channel: 'smtp' | 'admin';
    };
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type PostAuthForgotPasswordResponses = {
    /**
     * Reset request received
     */
    200: unknown;
};

export type PostAuthResetPasswordData = {
    body: {
        token: string;
        email: string;
        password: string;
        password_confirmation: string;
    };
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type PostAuthResetPasswordResponses = {
    /**
     * Password reset successful
     */
    200: unknown;
};

export type PostAuthChangePasswordData = {
    body: {
        current_password: string;
        password: string;
        password_confirmation: string;
    };
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type PostAuthChangePasswordResponses = {
    /**
     * Password changed successfully
     */
    200: unknown;
};

export type GetAuthSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sessions';
};

export type GetAuthSessionsResponses = {
    /**
     * List of sessions
     */
    200: Array<Session>;
};

export type GetAuthSessionsResponse = GetAuthSessionsResponses[keyof GetAuthSessionsResponses];

export type DeleteAuthSessionsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/auth/sessions/{id}';
};

export type DeleteAuthSessionsByIdResponses = {
    /**
     * Session revoked
     */
    200: unknown;
};

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutResponses = {
    /**
     * Logged out
     */
    200: unknown;
};

export type GetAuthProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/profile';
};

export type GetAuthProfileResponses = {
    /**
     * Profile
     */
    200: User;
};

export type GetAuthProfileResponse = GetAuthProfileResponses[keyof GetAuthProfileResponses];

export type PutAuthProfileData = {
    body: {
        name?: string;
        phone?: string;
        avatar_url?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/profile';
};

export type PutAuthProfileResponses = {
    /**
     * Updated Profile
     */
    200: User;
};

export type PutAuthProfileResponse = PutAuthProfileResponses[keyof PutAuthProfileResponses];

export type GetDirectoryData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        department_id?: number;
    };
    url: '/directory';
};

export type GetDirectoryResponses = {
    /**
     * Directory list
     */
    200: {
        data?: Array<User>;
    };
};

export type GetDirectoryResponse = GetDirectoryResponses[keyof GetDirectoryResponses];

export type GetOrgDepartmentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/org/departments';
};

export type GetOrgDepartmentsResponses = {
    /**
     * Departments
     */
    200: Array<Department>;
};

export type GetOrgDepartmentsResponse = GetOrgDepartmentsResponses[keyof GetOrgDepartmentsResponses];

export type PostOrgDepartmentsData = {
    body: {
        name?: string;
        description?: string;
    };
    path?: never;
    query?: never;
    url: '/org/departments';
};

export type PostOrgDepartmentsResponses = {
    /**
     * Created
     */
    201: Department;
};

export type PostOrgDepartmentsResponse = PostOrgDepartmentsResponses[keyof PostOrgDepartmentsResponses];

export type DeleteOrgDepartmentsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/org/departments/{id}';
};

export type DeleteOrgDepartmentsByIdResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteOrgDepartmentsByIdResponse = DeleteOrgDepartmentsByIdResponses[keyof DeleteOrgDepartmentsByIdResponses];

export type GetOrgDepartmentsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/org/departments/{id}';
};

export type GetOrgDepartmentsByIdResponses = {
    /**
     * Department
     */
    200: Department;
};

export type GetOrgDepartmentsByIdResponse = GetOrgDepartmentsByIdResponses[keyof GetOrgDepartmentsByIdResponses];

export type PutOrgDepartmentsByIdData = {
    body: {
        name?: string;
        description?: string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/org/departments/{id}';
};

export type PutOrgDepartmentsByIdResponses = {
    /**
     * Updated
     */
    200: Department;
};

export type PutOrgDepartmentsByIdResponse = PutOrgDepartmentsByIdResponses[keyof PutOrgDepartmentsByIdResponses];

export type PostOrgDepartmentsByDepartmentIdTeamsData = {
    body: {
        name?: string;
        description?: string;
    };
    path: {
        departmentId: number;
    };
    query?: never;
    url: '/org/departments/{departmentId}/teams';
};

export type PostOrgDepartmentsByDepartmentIdTeamsResponses = {
    /**
     * Created
     */
    201: Team;
};

export type PostOrgDepartmentsByDepartmentIdTeamsResponse = PostOrgDepartmentsByDepartmentIdTeamsResponses[keyof PostOrgDepartmentsByDepartmentIdTeamsResponses];

export type DeleteOrgDepartmentsByDepartmentIdTeamsByTeamIdData = {
    body?: never;
    path: {
        departmentId: number;
        teamId: number;
    };
    query?: never;
    url: '/org/departments/{departmentId}/teams/{teamId}';
};

export type DeleteOrgDepartmentsByDepartmentIdTeamsByTeamIdResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteOrgDepartmentsByDepartmentIdTeamsByTeamIdResponse = DeleteOrgDepartmentsByDepartmentIdTeamsByTeamIdResponses[keyof DeleteOrgDepartmentsByDepartmentIdTeamsByTeamIdResponses];

export type GetOrgDesignationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/org/designations';
};

export type GetOrgDesignationsResponses = {
    /**
     * Designations
     */
    200: Array<Designation>;
};

export type GetOrgDesignationsResponse = GetOrgDesignationsResponses[keyof GetOrgDesignationsResponses];

export type PostOrgDesignationsData = {
    body: {
        name?: string;
        description?: string;
    };
    path?: never;
    query?: never;
    url: '/org/designations';
};

export type PostOrgDesignationsResponses = {
    /**
     * Created
     */
    201: Designation;
};

export type PostOrgDesignationsResponse = PostOrgDesignationsResponses[keyof PostOrgDesignationsResponses];

export type DeleteOrgDesignationsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/org/designations/{id}';
};

export type DeleteOrgDesignationsByIdResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteOrgDesignationsByIdResponse = DeleteOrgDesignationsByIdResponses[keyof DeleteOrgDesignationsByIdResponses];

export type PutOrgDesignationsByIdData = {
    body: {
        name?: string;
        description?: string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/org/designations/{id}';
};

export type PutOrgDesignationsByIdResponses = {
    /**
     * Updated
     */
    200: Designation;
};

export type PutOrgDesignationsByIdResponse = PutOrgDesignationsByIdResponses[keyof PutOrgDesignationsByIdResponses];

export type GetOrgUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/org/users';
};

export type GetOrgUsersResponses = {
    /**
     * Users
     */
    200: Array<User>;
};

export type GetOrgUsersResponse = GetOrgUsersResponses[keyof GetOrgUsersResponses];

export type PostOrgUsersData = {
    body: {
        name?: string;
        email?: string;
        phone?: string;
        department_id?: number;
        team_id?: number;
        designation_id?: number;
        roles?: Array<string>;
    };
    path?: never;
    query?: never;
    url: '/org/users';
};

export type PostOrgUsersResponses = {
    /**
     * Created
     */
    201: User;
};

export type PostOrgUsersResponse = PostOrgUsersResponses[keyof PostOrgUsersResponses];

export type DeleteOrgUsersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/org/users/{id}';
};

export type DeleteOrgUsersByIdResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteOrgUsersByIdResponse = DeleteOrgUsersByIdResponses[keyof DeleteOrgUsersByIdResponses];

export type GetOrgUsersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/org/users/{id}';
};

export type GetOrgUsersByIdResponses = {
    /**
     * User
     */
    200: User;
};

export type GetOrgUsersByIdResponse = GetOrgUsersByIdResponses[keyof GetOrgUsersByIdResponses];

export type PutOrgUsersByIdData = {
    body: {
        name?: string;
        email?: string;
        phone?: string;
        department_id?: number;
        team_id?: number;
        designation_id?: number;
        status?: 'active' | 'inactive';
        roles?: Array<string>;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/org/users/{id}';
};

export type PutOrgUsersByIdResponses = {
    /**
     * Updated
     */
    200: User;
};

export type PutOrgUsersByIdResponse = PutOrgUsersByIdResponses[keyof PutOrgUsersByIdResponses];

export type PostAttendanceEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/attendance/events';
};

export type PostAttendanceEventsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAttendanceDaysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/attendance/days';
};

export type GetAttendanceDaysResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetLeaveRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/leave-requests';
};

export type GetLeaveRequestsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostLeaveRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/leave-requests';
};

export type PostLeaveRequestsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetChatConversationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/chat/conversations';
};

export type GetChatConversationsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetChatConversationsByIdMessagesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/chat/conversations/{id}/messages';
};

export type GetChatConversationsByIdMessagesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostChatConversationsByIdMessagesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/chat/conversations/{id}/messages';
};

export type PostChatConversationsByIdMessagesResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GetAdminSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/settings';
};

export type GetAdminSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutAdminSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/settings';
};

export type PutAdminSettingsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAdminAuditLogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/audit-logs';
};

export type GetAdminAuditLogsResponses = {
    /**
     * OK
     */
    200: unknown;
};
