[build]
builder = "nixpacks"
buildCommand = "php artisan config:clear && php artisan route:clear && php artisan view:clear && composer install --no-dev --optimize-autoloader"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
